package com.JAI.global.status;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.springframework.http.HttpStatus;

@Getter
@AllArgsConstructor
public enum ErrorStatus {
    // 공통 관련 에러
    BAD_REQUEST(HttpStatus.BAD_REQUEST, "COMMON400"),
    INVALID_LOGIN(HttpStatus.BAD_REQUEST, "COMMON401"),
    FORBIDDEN(HttpStatus.FORBIDDEN, "COMMON403"),
    NOT_FOUND(HttpStatus.NOT_FOUND, "COMMON404"),

    // 사용자 에러
    USER_NOT_FOUND(HttpStatus.NOT_FOUND, "USER404"),
    USER_DUPLICATED(HttpStatus.CONFLICT,"USER409"),
    USER_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "USER403"),
    USER_BAD_REQUEST(HttpStatus.BAD_REQUEST, "USER400"),

    // 카테고리 에러
    CATEGORY_NOT_FOUND(HttpStatus.NOT_FOUND, "CATEGORY404"),
    CATEGORY_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "CATEGORY403"),

    // 개인 일정 에러
    PERSONAL_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "CATEGORY404"),
    PERSONAL_EVENT_NOT_OWNER(HttpStatus.FORBIDDEN, "CATEGORY403"),
    PERSONAL_EVENT_BAD_REQUEST(HttpStatus.BAD_REQUEST, "CATEGORY400"),

    // 알람 에러
    ALARM_NOT_FOUND(HttpStatus.NOT_FOUND, "ALARM404"),

    // 챗봇 에러
    CHATBOT_BAD_REQUEST(HttpStatus.BAD_REQUEST, "CHATBOT400"),
    CHATBOT_FORBIDDEN(HttpStatus.FORBIDDEN, "CHATBOT403"),
    CHATBOT_NOT_FOUND(HttpStatus.NOT_FOUND, "CHATBOT404"),
    CHATBOT_UNPROCESSABLE_ENTITY(HttpStatus.UNPROCESSABLE_ENTITY, "CHATBOT422"),
  
    // 개인 투두 에러
    PERSONAL_TODO_NOT_FOUND(HttpStatus.NOT_FOUND, "TODO404"),
    PERSONAL_TODO_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "TODO403"),
    PERSONAL_TODO_BAD_REQUEST(HttpStatus.BAD_REQUEST, "TODO400"),

    //그룹
    GROUP_NOT_FOUND(HttpStatus.NOT_FOUND, "GROUP404"),
    GROUP_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "GROUP403"),
    GROUP_BAD_REQUEST(HttpStatus.BAD_REQUEST, "GROUP400"),

    //그룹 셋팅
    GROUP_SETTING_NOT_FOUND(HttpStatus.NOT_FOUND, "GROUP-SETTING404"),
    GROUP_SETTING_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "GROUP-SETTING403"),
    GROUP_SETTING_BAD_REQUEST(HttpStatus.BAD_REQUEST, "GROUP-SETTING400"),
    GROUP_SETTING_DUPLICATED(HttpStatus.CONFLICT,"GROUP-SETTING409"),
    GROUP_SETTING_ACCESS_DENIED(HttpStatus.FORBIDDEN,"GROUP-SETTING403"),

    //그룹 초대
    GROUP_INVITATION_ACCESS_DENIED(HttpStatus.FORBIDDEN,"GROUP-INVITATION403"),
    GROUP_INVITATION_DUPLICATED(HttpStatus.CONFLICT,"GROUP-INVITATION409"),
    GROUP_INVITATION_NOT_FOUND(HttpStatus.NOT_FOUND, "GROUP-INVITATION404"),

    // 그룹 알림
    GROUP_EVENT_NOT_FOUND(HttpStatus.NOT_FOUND, "GROUP-EVENT404"),

    // 그룹 투두
    GROUP_TODO_NOT_FOUND(HttpStatus.NOT_FOUND, "GROUP-TODO404"),
    GROUP_TODO_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "GROUP-TODO403"),
    GROUP_TODO_BAD_REQUEST(HttpStatus.BAD_REQUEST, "GROUP-TODO400"),

    // 그룹 투두 맵핑
    GROUP_TODO_MAPPING_NOT_OWNER_FOUND(HttpStatus.FORBIDDEN, "GROUP-TODO-MAPPING403"),

    //JWT
    REFRESH_TOKEN_NOT_FOUND(HttpStatus.NOT_FOUND,"REFRESH-TOKEN404"),
    REFRESH_TOKEN_UNAUTHORIZED(HttpStatus.UNAUTHORIZED,"REFRESH-TOKEN401"),
    REFRESH_TOKEN_BAD_REQUEST(HttpStatus.BAD_REQUEST,"REFRESH-TOKEN400"),
    REFRESH_TOKEN_FORBIDDEN(HttpStatus.FORBIDDEN,"REFRESH-TOKEN403"),
    ACCESS_TOKEN_UNAUTHORIZED(HttpStatus.UNAUTHORIZED,"ACCESS_TOKEN401"),
    LOGIN_REQUEST_BAD_REQUEST(HttpStatus.BAD_REQUEST,"LOGIN-REQUEST400");


    private final HttpStatus httpStatus;
    private final String code;
}
